# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eaf084782b53527b929e87046a518e8f9b8c263d1372e1d70b412d0c9889327bcd146a591fd9b814be9f5c0bcb7adc14c91f54c588231c5cb67eccc115f2177e

test:
  secret_key_base: 243e18d4599a9ded4d0dc8d268076a2115c78b5a5afb1b5f665ae2089a6d4a166605b57d7ef869c6ee41ccaf8584f3a135cc55bbc93e2e62a3564c00661c3c7b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
