---
- hosts: all
  remote_user: root
  vars_files:
    - config.yml
  roles:
    - init
    - exim4
    - role: rvm
      rvm1_rvm_version: 'stable'
      rvm1_rvm_check_for_updates: true
      rvm1_rubies:
        - 'ruby-2.3.1'
      rvm1_install_flags: '--auto-dotfiles --user-install'
      rvm1_install_path: '/home/deployer/.rvm'
      rvm1_user: 'deployer'
      tags: rvm
